"""empty message

Revision ID: 08fa8bd94654
Revises: 
Create Date: 2019-10-10 14:22:25.976961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08fa8bd94654'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_time'), 'user', ['created_time'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=120), nullable=True),
    sa.Column('pay_offer', sa.Float(asdecimal=True), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('job_description', sa.String(length=500), nullable=True),
    sa.Column('date', sa.String(length=25), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_contact_email'), 'offer', ['contact_email'], unique=False)
    op.create_index(op.f('ix_offer_job_title'), 'offer', ['job_title'], unique=False)
    op.create_index(op.f('ix_offer_pay_offer'), 'offer', ['pay_offer'], unique=False)
    op.create_index(op.f('ix_offer_timestamp'), 'offer', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offer_timestamp'), table_name='offer')
    op.drop_index(op.f('ix_offer_pay_offer'), table_name='offer')
    op.drop_index(op.f('ix_offer_job_title'), table_name='offer')
    op.drop_index(op.f('ix_offer_contact_email'), table_name='offer')
    op.drop_table('offer')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_created_time'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
